import { formatDate12Hours } from "./dates.js"

function sanitizeCompetence(str) {
  if (!str) return "";
  let s = String(str).trim();
  s = s.split(/ELEMENTO\(S\)|DENOMINACI[OÓ]N|DESCRIPCI[OÓ]N/i)[0].trim();
  const dotIdx = s.indexOf(".");
  if (dotIdx > 5) {
    s = s.slice(0, dotIdx + 1).trim();
  }
  while (/\s+[A-Z][\.\,\;\:]?$/i.test(s)) {
    s = s.replace(/\s+[A-Z][\.\,\;\:]?$/i, "").trim();
  }
  return s;
}

function sanitizeOutcome(str) {
  if (!str) return "";
  let s = String(str).trim();
  s = s.split(/ELEMENTO\(S\)|DENOMINACI[OÓ]N|DESCRIPCI[OÓ]N/i)[0].trim();
  const dotIdx = s.indexOf(".");
  if (dotIdx > 5) {
    s = s.slice(0, dotIdx + 1).trim();
  }
  while (/\s+[A-Z][\.\,\;\:]?$/i.test(s)) {
    s = s.replace(/\s+[A-Z][\.\,\;\:]?$/i, "").trim();
  }
  return s;
}

function formatEventSchedule(schedule, event, index, color, autogenerated, title = null) {
    const ficheNumber = String(schedule.fiche?.number || schedule.complementaryRequest?.fichaNumber || schedule.complementaryRequest?.fichaCaracterizacion || "SIN_FICHA");
    const programName = String(schedule.program?.name || schedule.complementaryRequest?.catalogCourseName || "CURSO COMPLEMENTARIO");
    const envName = String(schedule.environment?.name || schedule.complementaryRequest?.ambienteNombre || "SIN ASIGNAR");
    
    const evDate = new Date(event);
    const startStr = !isNaN(evDate.getTime()) ? evDate.toISOString().split("T")[0] : "";

    // 1. Competencia limpia (sin repeticiones duplicadas)
    const session = schedule.complementaryRequest?.sesiones?.find(s => s.fecha === startStr);
    const compArray = schedule.complementaryRequest?.sesiones?.map(s => s.competencia).filter(Boolean) || [];
    const uniqueComps = Array.from(new Set(compArray));
    const compName = sanitizeCompetence(
      schedule.competence?.name ||
      session?.competencia ||
      (uniqueComps.length > 0 ? uniqueComps.join(", ") : "COMPETENCIA COMPLEMENTARIA")
    );

    // 2. Resultado de aprendizaje específico por fecha de clase (evento)
    let outcomeVal = schedule.outcome?.outcomes || "";
    if (!outcomeVal && schedule.complementaryRequest) {
      const compReq = schedule.complementaryRequest;
      const sessionRes = session?.resultados?.filter(Boolean) || [];
      if (sessionRes.length > 0) {
        outcomeVal = sessionRes.join(", ");
      } else if (compReq.outcomes?.length > 0) {
        const validOutcomes = compReq.outcomes.filter(Boolean);
        if (validOutcomes.length > 0) {
          const totalEvents = (schedule.events || []).length || 1;
          const currentEvIdx = (schedule.events || []).findIndex(e => {
            const d = new Date(e);
            return !isNaN(d.getTime()) && d.toISOString().split("T")[0] === startStr;
          });
          const evIdx = currentEvIdx >= 0 ? currentEvIdx : Math.max(0, index - 1);
          const outcomeIdx = Math.min(
            Math.floor((evIdx * validOutcomes.length) / totalEvents),
            validOutcomes.length - 1
          );
          outcomeVal = validOutcomes[outcomeIdx];
        }
      } else {
        const outcomesArray = compReq.sesiones?.flatMap(s => s.resultados || []).filter(Boolean) || [];
        const uniqueOutcomes = Array.from(new Set(outcomesArray));
        if (uniqueOutcomes.length > 0) {
          outcomeVal = uniqueOutcomes.join(", ");
        }
      }
    }
    if (!outcomeVal) outcomeVal = "SIN RESULTADO ASIGNADO";
    outcomeVal = sanitizeOutcome(outcomeVal);
    
    const instructorId = String(schedule.instructor?._id || "");
    const instructorName = String(schedule.instructor?.name || "SIN ASIGNAR");
    const titleVal = String(title || instructorName);

    return {
        id: Number(index),
        code: String(schedule._id || ""),
        fiche: ficheNumber,
        idInstructor: instructorId,
        instructor: instructorName,
        title: titleVal,
        program: programName,
        supporttext: String(schedule.supporttext || ""),
        observation: String(schedule.observation || ""),
        environment: envName,
        outcome: outcomeVal,
        competence: compName,
        start: startStr,
        tstart: formatDate12Hours(schedule.tstart),
        tend: formatDate12Hours(schedule.tend),
        backgroundColor: String(color?.background || "#4e73df"),
        borderColor: String(color?.background || "#4e73df"),
        textColor: String(color?.colortext || "#ffffff"),
        type: 0,
        autogenerated: Boolean(autogenerated)
    };
}

function formatEventOtherSchedule(schedule, event, index, color, autogenerated) {
    const evDate = new Date(event);
    const startStr = !isNaN(evDate.getTime()) ? evDate.toISOString().split("T")[0] : "";

    return {
        id: Number(index),
        code: String(schedule._id || ""),
        idInstructor: String(schedule.instructor?._id || ""),
        typeactivity: String(schedule.typeactivity || ""),
        additionalactivity: String(schedule.additionalactivity || ""),
        justification: String(schedule.justification || ""),
        title: String(schedule.instructor?.name || "SIN ASIGNAR"),
        start: startStr,
        tstart: formatDate12Hours(schedule.tstart),
        tend: formatDate12Hours(schedule.tend),
        backgroundColor: String(color?.background || "#4e73df"),
        borderColor: String(color?.background || "#4e73df"),
        textColor: String(color?.colortext || "#ffffff"),
        type: 1,
        autogenerated: Boolean(autogenerated)
    };
}



export {formatEventSchedule,formatEventOtherSchedule}